import type { Metadata } from "next";
import "../globals.css";
import { NavBar } from "@/components";

export const metadata: Metadata = {
  title: "KlowHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased home_bg h-full min-h-screen`}>
        <NavBar />
        <main className="flex flex-col mx-8 pt-8 gap-8">
          {children}
        </main>
      </body>
    </html>
  );
}