import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/organisms/NavBar/navbar";

export const metadata: Metadata = {
  title: "KlowHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased home_bg h-full`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}