import type { Metadata } from "next";
import "../globals.css";
import { DashboardCard, DashboardCardList, NavBar } from "@/components";
import Link from "next/link";
import { Heart, LibraryBig, Mail } from "lucide-react";
import AgentIcon from "@/components/atoms/icons/agent-icon";

export const metadata: Metadata = {
  title: "KlowHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased home_bg h-full min-h-screen`}>
        <NavBar />
        <main className="flex flex-col mx-8 pt-8 gap-8">
          {/* to-do-> replace w/proper component */}
          <DashboardCardList />
          {children}
        </main>
      </body>
    </html>
  );
}